### ISSUE TITLE
How should I use this project from npm

### ISSUE THREAD

**Issue by Wyatex** [web-infra-dev/rspack-sources#61]
I've searched all over the npm official website and found that this project does not exist. As a front-end developer, how should I use this project?

**Comment by Boshen** [comment]
Can you describe your use case? This package is meant to be consumed by Rspack, on the Rust side as a crate.

**Comment by Wyatex** [comment]
There is a tool called unocss, which does not currently support rspack. I plan to provide support for rspack, but this tool uses a package called webpack-source, so I think I need rspack-source to enhance support.

**Comment by Boshen** [comment]
@Wyatex Can you point us to where `webpack-source` is being used in `unocss`? It would be great if you can find the call site in `unocss` so we can help you impement this in Rspack.

**Comment by Wyatex** [comment]
https://github.com/unocss/unocss/blob/main/packages/webpack/src/index.ts#L127-L127

Moreover, this tool uses the resolveId hook, which in webpack is realized by the webpack-virtual-modules package. And for instance, unplugin-icons also needs to use virtual modules, so is it possible to also implement an rspack-virtual-modules?

**Comment by Boshen** [comment]
@web-infra-dev/rspack-dx Please take a look.

**Comment by ahabhgk** [comment]
This crate is only used in Rust side, for JS side `webpack-sources` should works

For unocss plugin (or other common used plugins), Rspack should be able to run its webpack plugin directly for the long term, and for the short term, it's welcome for someone to create a rspack-specific plugin for unocss

And there is a [webpack-virtual-modules alternative for rspack](https://github.com/rspack-contrib/rspack-plugins/tree/main/packages/plugin-virtual-module)

**Comment by ahabhgk** [comment]
Feel free to reopen if you have any further questions
